#!/usr/bin/env python3
"""
gen_debug.py
读取 debug_config.json，生成 debug_config.h
同时根据 USE_BOOTLOADER 自动切换链接脚本
"""

import json
import os
import re

CONFIG_FILE = os.path.join(os.path.dirname(__file__), "debug_config.json")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "App", "debug_config.h")
LD_FILE     = os.path.join(os.path.dirname(__file__), "n32l403.ld")

def update_ld(use_bootloader: bool):
    """根据 USE_BOOTLOADER 切换链接脚本的 Flash 起始地址和大小"""
    if use_bootloader:
        origin, length = "0x08004000", "48K"
        label = "with bootloader (Slot A)"
    else:
        origin, length = "0x08000000", "128K"
        label = "standalone (debug)"

    with open(LD_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    new_content = re.sub(
        r'(FLASH\s*\(rx\)\s*:\s*ORIGIN\s*=\s*)0x[0-9A-Fa-f]+(\s*,\s*LENGTH\s*=\s*)\w+',
        rf'\g<1>{origin}\g<2>{length}',
        content
    )

    if new_content != content:
        with open(LD_FILE, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"[gen_debug] LD updated: FLASH ORIGIN={origin} LENGTH={length} ({label})")
    else:
        print(f"[gen_debug] LD unchanged ({label})")

def main():
    with open(CONFIG_FILE, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    options = cfg.get("options", {})
    use_bootloader = options.get("USE_BOOTLOADER", False)

    # 自动切换链接脚本
    update_ld(use_bootloader)

    lines = [
        "/* Auto-generated by gen_debug.py — DO NOT EDIT */",
        "/* Source: debug_config.json */",
        "#ifndef __DEBUG_CONFIG_H__",
        "#define __DEBUG_CONFIG_H__",
        "",
        "#include <rtthread.h>",
        "",
        "/* ---- 模块调试开关 ---- */",
    ]

    for mod, enabled in cfg.get("modules", {}).items():
        if mod.startswith("comment"):
            continue
        val = "1" if enabled else "0"
        lines.append(f"#define DBG_{mod.upper():<16} {val}")

    lines += ["", "/* ---- 调试选项 ---- */"]

    for key, val in options.items():
        if key.startswith("comment"):
            continue
        if isinstance(val, bool):
            lines.append(f"#define DBG_{key:<20} {'1' if val else '0'}")
        elif isinstance(val, int):
            lines.append(f"#define DBG_{key:<20} {val}")

    lines += [
        "",
        "/* ---- 日志宏 ---- */",
        "#define DLOG(tag, mod_flag, fmt, ...) \\",
        "    do { if (mod_flag) rt_kprintf(\"[\" tag \"] \" fmt \"\\n\", ##__VA_ARGS__); } while(0)",
        "",
        "#if DBG_LOG_LEVEL >= 3",
        "#define DDBG(tag, en, fmt, ...) DLOG(tag, en, fmt, ##__VA_ARGS__)",
        "#else",
        "#define DDBG(tag, en, fmt, ...) do {} while(0)",
        "#endif",
        "",
        "#if DBG_LOG_LEVEL >= 2",
        "#define DINF(tag, en, fmt, ...) DLOG(tag, en, fmt, ##__VA_ARGS__)",
        "#else",
        "#define DINF(tag, en, fmt, ...) do {} while(0)",
        "#endif",
        "",
        "#if DBG_LOG_LEVEL >= 1",
        "#define DERR(tag, en, fmt, ...) DLOG(tag, en, fmt, ##__VA_ARGS__)",
        "#else",
        "#define DERR(tag, en, fmt, ...) do {} while(0)",
        "#endif",
        "",
        "#endif /* __DEBUG_CONFIG_H__ */",
    ]

    content = "\n".join(lines) + "\n"

    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            if f.read() == content:
                print(f"[gen_debug] {OUTPUT_FILE} unchanged, skip.")
                return

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[gen_debug] Generated: {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
